- path: /configuration-hub/object-mappings/{sourceOrg}
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#create-object-mapping
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.object_mapping_request import ObjectMappingRequest
        from sailpoint.v3.models.object_mapping_response import ObjectMappingResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          source_org = 'source-org' # str | The name of the source org. # str | The name of the source org.
          object_mapping_request = '''{
          "targetValue" : "My New Governance Group Name",
          "jsonPath" : "$.name",
          "sourceValue" : "My Governance Group Name",
          "enabled" : false,
          "objectType" : "IDENTITY"
        }''' # ObjectMappingRequest | The object mapping request body.
          try:
              # Creates an object mapping
              new_object_mapping_request = ObjectMappingRequest.from_json(object_mapping_request)
              results = ConfigurationHubApi(api_client).create_object_mapping(source_org=source_org, object_mapping_request=new_object_mapping_request)
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).create_object_mapping(source_org, new_object_mapping_request)
              print("The response of ConfigurationHubApi->create_object_mapping:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->create_object_mapping: %s\n" % e)
- path: /configuration-hub/object-mappings/{sourceOrg}/bulk-create
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#create-object-mappings
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.object_mapping_bulk_create_request import ObjectMappingBulkCreateRequest
        from sailpoint.v3.models.object_mapping_bulk_create_response import ObjectMappingBulkCreateResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          source_org = 'source-org' # str | The name of the source org. # str | The name of the source org.
          object_mapping_bulk_create_request = '''{
          "newObjectsMappings" : [ {
            "targetValue" : "My New Governance Group Name",
            "jsonPath" : "$.name",
            "sourceValue" : "My Governance Group Name",
            "enabled" : false,
            "objectType" : "IDENTITY"
          }, {
            "targetValue" : "My New Governance Group Name",
            "jsonPath" : "$.name",
            "sourceValue" : "My Governance Group Name",
            "enabled" : false,
            "objectType" : "IDENTITY"
          } ]
        }''' # ObjectMappingBulkCreateRequest | The bulk create object mapping request body.
          try:
              # Bulk creates object mappings
              new_object_mapping_bulk_create_request = ObjectMappingBulkCreateRequest.from_json(object_mapping_bulk_create_request)
              results = ConfigurationHubApi(api_client).create_object_mappings(source_org=source_org, object_mapping_bulk_create_request=new_object_mapping_bulk_create_request)
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).create_object_mappings(source_org, new_object_mapping_bulk_create_request)
              print("The response of ConfigurationHubApi->create_object_mappings:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->create_object_mappings: %s\n" % e)
- path: /configuration-hub/backups/uploads
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#create-uploaded-configuration
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.backup_response import BackupResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          data = None # bytearray | JSON file containing the objects to be imported. # bytearray | JSON file containing the objects to be imported.
          name = 'name_example' # str | Name that will be assigned to the uploaded configuration file. # str | Name that will be assigned to the uploaded configuration file.
          try:
              # Upload a Configuration
              
              results = ConfigurationHubApi(api_client).create_uploaded_configuration(data=data, name=name)
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).create_uploaded_configuration(data, name)
              print("The response of ConfigurationHubApi->create_uploaded_configuration:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->create_uploaded_configuration: %s\n" % e)
- path: /configuration-hub/object-mappings/{sourceOrg}/{objectMappingId}
  method: DELETE
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#delete-object-mapping
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          source_org = 'source-org' # str | The name of the source org. # str | The name of the source org.
          object_mapping_id = '3d6e0144-963f-4bd6-8d8d-d77b4e507ce4' # str | The id of the object mapping to be deleted. # str | The id of the object mapping to be deleted.
          try:
              # Deletes an object mapping
              
              ConfigurationHubApi(api_client).delete_object_mapping(source_org=source_org, object_mapping_id=object_mapping_id)
              # Below is a request that includes all optional parameters
              # ConfigurationHubApi(api_client).delete_object_mapping(source_org, object_mapping_id)
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->delete_object_mapping: %s\n" % e)
- path: /configuration-hub/backups/uploads/{id}
  method: DELETE
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#delete-uploaded-configuration
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          id = '3d0fe04b-57df-4a46-a83b-8f04b0f9d10b' # str | The id of the uploaded configuration. # str | The id of the uploaded configuration.
          try:
              # Delete an Uploaded Configuration
              
              ConfigurationHubApi(api_client).delete_uploaded_configuration(id=id)
              # Below is a request that includes all optional parameters
              # ConfigurationHubApi(api_client).delete_uploaded_configuration(id)
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->delete_uploaded_configuration: %s\n" % e)
- path: /configuration-hub/object-mappings/{sourceOrg}
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#get-object-mappings
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.object_mapping_response import ObjectMappingResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          source_org = 'source-org' # str | The name of the source org. # str | The name of the source org.
          try:
              # Gets list of object mappings
              
              results = ConfigurationHubApi(api_client).get_object_mappings(source_org=source_org)
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).get_object_mappings(source_org)
              print("The response of ConfigurationHubApi->get_object_mappings:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->get_object_mappings: %s\n" % e)
- path: /configuration-hub/backups/uploads/{id}
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#get-uploaded-configuration
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.backup_response import BackupResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          id = '3d0fe04b-57df-4a46-a83b-8f04b0f9d10b' # str | The id of the uploaded configuration. # str | The id of the uploaded configuration.
          try:
              # Get an Uploaded Configuration
              
              results = ConfigurationHubApi(api_client).get_uploaded_configuration(id=id)
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).get_uploaded_configuration(id)
              print("The response of ConfigurationHubApi->get_uploaded_configuration:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->get_uploaded_configuration: %s\n" % e)
- path: /configuration-hub/backups/uploads
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#list-uploaded-configurations
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.backup_response import BackupResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          filters = 'status eq \"COMPLETE\"' # str | Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **status**: *eq* (optional) # str | Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **status**: *eq* (optional)
          try:
              # List Uploaded Configurations
              
              results = ConfigurationHubApi(api_client).list_uploaded_configurations()
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).list_uploaded_configurations(filters)
              print("The response of ConfigurationHubApi->list_uploaded_configurations:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->list_uploaded_configurations: %s\n" % e)
- path: /configuration-hub/object-mappings/{sourceOrg}/bulk-patch
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/configuration-hub#update-object-mappings
      source: |
        from sailpoint.v3.api.configuration_hub_api import ConfigurationHubApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.object_mapping_bulk_patch_request import ObjectMappingBulkPatchRequest
        from sailpoint.v3.models.object_mapping_bulk_patch_response import ObjectMappingBulkPatchResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          source_org = 'source-org' # str | The name of the source org. # str | The name of the source org.
          object_mapping_bulk_patch_request = '''{
          "patches" : {
            "603b1a61-d03d-4ed1-864f-a508fbd1995d" : [ {
              "op" : "replace",
              "path" : "/enabled",
              "value" : true
            } ],
            "00bece34-f50d-4227-8878-76f620b5a971" : [ {
              "op" : "replace",
              "path" : "/targetValue",
              "value" : "New Target Value"
            } ]
          }
        }''' # ObjectMappingBulkPatchRequest | The object mapping request body.
          try:
              # Bulk updates object mappings
              new_object_mapping_bulk_patch_request = ObjectMappingBulkPatchRequest.from_json(object_mapping_bulk_patch_request)
              results = ConfigurationHubApi(api_client).update_object_mappings(source_org=source_org, object_mapping_bulk_patch_request=new_object_mapping_bulk_patch_request)
              # Below is a request that includes all optional parameters
              # results = ConfigurationHubApi(api_client).update_object_mappings(source_org, new_object_mapping_bulk_patch_request)
              print("The response of ConfigurationHubApi->update_object_mappings:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling ConfigurationHubApi->update_object_mappings: %s\n" % e)
