- path: /mfa/{method}/delete
  method: DELETE
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#delete-mfa-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.mfa_okta_config import MfaOktaConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          method = 'okta-verify' # str | The name of the MFA method. The currently supported method names are 'okta-verify' and 'duo-web'. # str | The name of the MFA method. The currently supported method names are 'okta-verify' and 'duo-web'.
          try:
              # Delete MFA method configuration
              
              results = MFAConfigurationApi(api_client).delete_mfa_config(method=method)
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).delete_mfa_config(method)
              print("The response of MFAConfigurationApi->delete_mfa_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->delete_mfa_config: %s\n" % e)
- path: /mfa/duo-web/config
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#get-mfa-duo-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.mfa_duo_config import MfaDuoConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          try:
              # Configuration of Duo MFA method
              
              results = MFAConfigurationApi(api_client).get_mfa_duo_config()
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).get_mfa_duo_config()
              print("The response of MFAConfigurationApi->get_mfa_duo_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->get_mfa_duo_config: %s\n" % e)
- path: /mfa/kba/config
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#get-mfa-kba-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.kba_question import KbaQuestion
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          all_languages = allLanguages=true # bool | Indicator whether the question text should be returned in all configured languages    * If true, the question text is returned in all languages that it is configured in.    * If false, the question text is returned in the user locale if available, else for the default locale.     * If not passed, it behaves the same way as passing this parameter as false (optional) # bool | Indicator whether the question text should be returned in all configured languages    * If true, the question text is returned in all languages that it is configured in.    * If false, the question text is returned in the user locale if available, else for the default locale.     * If not passed, it behaves the same way as passing this parameter as false (optional)
          try:
              # Configuration of KBA MFA method
              
              results = MFAConfigurationApi(api_client).get_mfa_kba_config()
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).get_mfa_kba_config(all_languages)
              print("The response of MFAConfigurationApi->get_mfa_kba_config:\n")
              for item in results:
                  print(item.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->get_mfa_kba_config: %s\n" % e)
- path: /mfa/okta-verify/config
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#get-mfa-okta-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.mfa_okta_config import MfaOktaConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          try:
              # Configuration of Okta MFA method
              
              results = MFAConfigurationApi(api_client).get_mfa_okta_config()
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).get_mfa_okta_config()
              print("The response of MFAConfigurationApi->get_mfa_okta_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->get_mfa_okta_config: %s\n" % e)
- path: /mfa/duo-web/config
  method: PUT
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#set-mfa-duo-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.mfa_duo_config import MfaDuoConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          mfa_duo_config = '''{
          "accessKey" : "qw123Y3QlA5UqocYpdU3rEkzrK2D497y",
          "host" : "example.com",
          "configProperties" : {
            "skey" : "qwERttyZx1CdlQye2Vwtbsjr3HKddy4BAiCXjc5x",
            "ikey" : "Q123WE45R6TY7890ZXCV"
          },
          "mfaMethod" : "duo-web",
          "enabled" : true,
          "identityAttribute" : "email"
        }''' # MfaDuoConfig | 
          try:
              # Set Duo MFA configuration
              new_mfa_duo_config = MfaDuoConfig.from_json(mfa_duo_config)
              results = MFAConfigurationApi(api_client).set_mfa_duo_config(mfa_duo_config=new_mfa_duo_config)
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).set_mfa_duo_config(new_mfa_duo_config)
              print("The response of MFAConfigurationApi->set_mfa_duo_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->set_mfa_duo_config: %s\n" % e)
- path: /mfa/okta-verify/config
  method: PUT
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#set-mfa-okta-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.mfa_okta_config import MfaOktaConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          mfa_okta_config = '''{
          "accessKey" : "qw123Y3QlA5UqocYpdU3rEkzrK2D497y",
          "host" : "example.com",
          "mfaMethod" : "okta-verify",
          "enabled" : true,
          "identityAttribute" : "email"
        }''' # MfaOktaConfig | 
          try:
              # Set Okta MFA configuration
              new_mfa_okta_config = MfaOktaConfig.from_json(mfa_okta_config)
              results = MFAConfigurationApi(api_client).set_mfa_okta_config(mfa_okta_config=new_mfa_okta_config)
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).set_mfa_okta_config(new_mfa_okta_config)
              print("The response of MFAConfigurationApi->set_mfa_okta_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->set_mfa_okta_config: %s\n" % e)
- path: /mfa/kba/config/answers
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#set-mfakba-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.kba_answer_request_item import KbaAnswerRequestItem
        from sailpoint.v3.models.kba_answer_response_item import KbaAnswerResponseItem
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          kba_answer_request_item = '''[{id=173423, answer=822cd15d6c15aa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a0859a2fea34}, {id=c54fee53-2d63-4fc5-9259-3e93b9994135, answer=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08}]''' # List[KbaAnswerRequestItem] | 
          try:
              # Set MFA KBA configuration
              new_kba_answer_request_item = KbaAnswerRequestItem.from_json(kba_answer_request_item)
              results = MFAConfigurationApi(api_client).set_mfakba_config(kba_answer_request_item=new_kba_answer_request_item)
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).set_mfakba_config(new_kba_answer_request_item)
              print("The response of MFAConfigurationApi->set_mfakba_config:\n")
              for item in results:
                  print(item.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->set_mfakba_config: %s\n" % e)
- path: /mfa/{method}/test
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/mfa-configuration#test-mfa-config
      source: |
        from sailpoint.v3.api.mfa_configuration_api import MFAConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.mfa_config_test_response import MfaConfigTestResponse
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          method = 'okta-verify' # str | The name of the MFA method. The currently supported method names are 'okta-verify' and 'duo-web'. # str | The name of the MFA method. The currently supported method names are 'okta-verify' and 'duo-web'.
          try:
              # MFA method's test configuration
              
              results = MFAConfigurationApi(api_client).test_mfa_config(method=method)
              # Below is a request that includes all optional parameters
              # results = MFAConfigurationApi(api_client).test_mfa_config(method)
              print("The response of MFAConfigurationApi->test_mfa_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling MFAConfigurationApi->test_mfa_config: %s\n" % e)
