- path: /password-org-config
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/password-configuration#create-password-org-config
      source: |
        from sailpoint.v3.api.password_configuration_api import PasswordConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.password_org_config import PasswordOrgConfig
        from pprint import pprint
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
        password_org_config = '''{
          "digitTokenLength" : 9,
          "digitTokenEnabled" : true,
          "digitTokenDurationMinutes" : 10,
          "customInstructionsEnabled" : true
        }''' # PasswordOrgConfig | 
        try:
            # Create Password Org Config
            new_password_org_config = PasswordOrgConfig.from_json(password_org_config)
            results = PasswordConfigurationApi(api_client).create_password_org_config(password_org_config=new_password_org_config)
            # Below is a request that includes all optional parameters
            # results = PasswordConfigurationApi(api_client).create_password_org_config(new_password_org_config)
            print("The response of PasswordConfigurationApi->create_password_org_config:\n")
            pprint(results)
        except Exception as e:
            print("Exception when calling PasswordConfigurationApi->create_password_org_config: %s\n" % e)
- path: /password-org-config
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/password-configuration#get-password-org-config
      source: |
        from sailpoint.v3.api.password_configuration_api import PasswordConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.password_org_config import PasswordOrgConfig
        from pprint import pprint
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
        try:
            # Get Password Org Config
            
            results = PasswordConfigurationApi(api_client).get_password_org_config()
            # Below is a request that includes all optional parameters
            # results = PasswordConfigurationApi(api_client).get_password_org_config()
            print("The response of PasswordConfigurationApi->get_password_org_config:\n")
            pprint(results)
        except Exception as e:
            print("Exception when calling PasswordConfigurationApi->get_password_org_config: %s\n" % e)
- path: /password-org-config
  method: PUT
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/password-configuration#put-password-org-config
      source: |
        from sailpoint.v3.api.password_configuration_api import PasswordConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.password_org_config import PasswordOrgConfig
        from pprint import pprint
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
        password_org_config = '''{
          "digitTokenLength" : 9,
          "digitTokenEnabled" : true,
          "digitTokenDurationMinutes" : 10,
          "customInstructionsEnabled" : true
        }''' # PasswordOrgConfig | 
        try:
            # Update Password Org Config
            new_password_org_config = PasswordOrgConfig.from_json(password_org_config)
            results = PasswordConfigurationApi(api_client).put_password_org_config(password_org_config=new_password_org_config)
            # Below is a request that includes all optional parameters
            # results = PasswordConfigurationApi(api_client).put_password_org_config(new_password_org_config)
            print("The response of PasswordConfigurationApi->put_password_org_config:\n")
            pprint(results)
        except Exception as e:
            print("Exception when calling PasswordConfigurationApi->put_password_org_config: %s\n" % e)
