- path: /public-identities-config
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/public-identities-config#get-public-identity-config
      source: |
        from sailpoint.v3.api.public_identities_config_api import PublicIdentitiesConfigApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.public_identity_config import PublicIdentityConfig
        from pprint import pprint
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
        try:
            # Get the Public Identities Configuration
            
            results = PublicIdentitiesConfigApi(api_client).get_public_identity_config()
            # Below is a request that includes all optional parameters
            # results = PublicIdentitiesConfigApi(api_client).get_public_identity_config()
            print("The response of PublicIdentitiesConfigApi->get_public_identity_config:\n")
            pprint(results)
        except Exception as e:
            print("Exception when calling PublicIdentitiesConfigApi->get_public_identity_config: %s\n" % e)
- path: /public-identities-config
  method: PUT
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/public-identities-config#update-public-identity-config
      source: |
        from sailpoint.v3.api.public_identities_config_api import PublicIdentitiesConfigApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.public_identity_config import PublicIdentityConfig
        from pprint import pprint
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
        public_identity_config = '''{
          "modified" : "2018-06-25T20:22:28.104Z",
          "attributes" : [ {
            "name" : "Country",
            "key" : "country"
          }, {
            "name" : "Country",
            "key" : "country"
          } ],
          "modifiedBy" : {
            "name" : "Thomas Edison",
            "id" : "2c9180a46faadee4016fb4e018c20639",
            "type" : "IDENTITY"
          }
        }''' # PublicIdentityConfig | 
        try:
            # Update the Public Identities Configuration
            new_public_identity_config = PublicIdentityConfig.from_json(public_identity_config)
            results = PublicIdentitiesConfigApi(api_client).update_public_identity_config(public_identity_config=new_public_identity_config)
            # Below is a request that includes all optional parameters
            # results = PublicIdentitiesConfigApi(api_client).update_public_identity_config(new_public_identity_config)
            print("The response of PublicIdentitiesConfigApi->update_public_identity_config:\n")
            pprint(results)
        except Exception as e:
            print("Exception when calling PublicIdentitiesConfigApi->update_public_identity_config: %s\n" % e)
