- path: /accounts/search-attribute-config
  method: POST
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/search-attribute-configuration#create-search-attribute-config
      source: |
        from sailpoint.v3.api.search_attribute_configuration_api import SearchAttributeConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.search_attribute_config import SearchAttributeConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          search_attribute_config = '''{
          "displayName" : "New Mail Attribute",
          "name" : "newMailAttribute",
          "applicationAttributes" : {
            "2c91808b79fd2422017a0b35d30f3968" : "employeeNumber",
            "2c91808b79fd2422017a0b36008f396b" : "employeeNumber"
          }
        }''' # SearchAttributeConfig | 
          try:
              # Create Extended Search Attributes
              new_search_attribute_config = SearchAttributeConfig.from_json(search_attribute_config)
              results = SearchAttributeConfigurationApi(api_client).create_search_attribute_config(search_attribute_config=new_search_attribute_config)
              # Below is a request that includes all optional parameters
              # results = SearchAttributeConfigurationApi(api_client).create_search_attribute_config(new_search_attribute_config)
              print("The response of SearchAttributeConfigurationApi->create_search_attribute_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling SearchAttributeConfigurationApi->create_search_attribute_config: %s\n" % e)
- path: /accounts/search-attribute-config/{name}
  method: DELETE
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/search-attribute-configuration#delete-search-attribute-config
      source: |
        from sailpoint.v3.api.search_attribute_configuration_api import SearchAttributeConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          name = 'newMailAttribute' # str | Name of the extended search attribute configuration to delete. # str | Name of the extended search attribute configuration to delete.
          try:
              # Delete Extended Search Attribute
              
              SearchAttributeConfigurationApi(api_client).delete_search_attribute_config(name=name)
              # Below is a request that includes all optional parameters
              # SearchAttributeConfigurationApi(api_client).delete_search_attribute_config(name)
          except Exception as e:
              print("Exception when calling SearchAttributeConfigurationApi->delete_search_attribute_config: %s\n" % e)
- path: /accounts/search-attribute-config
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/search-attribute-configuration#get-search-attribute-config
      source: |
        from sailpoint.v3.api.search_attribute_configuration_api import SearchAttributeConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.search_attribute_config import SearchAttributeConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          limit = 250 # int | Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. (optional) (default to 250) # int | Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. (optional) (default to 250)
          offset = 0 # int | Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. (optional) (default to 0) # int | Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information. (optional) (default to 0)
          try:
              # List Extended Search Attributes
              
              results = SearchAttributeConfigurationApi(api_client).get_search_attribute_config()
              # Below is a request that includes all optional parameters
              # results = SearchAttributeConfigurationApi(api_client).get_search_attribute_config(limit, offset)
              print("The response of SearchAttributeConfigurationApi->get_search_attribute_config:\n")
              for item in results:
                  print(item.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling SearchAttributeConfigurationApi->get_search_attribute_config: %s\n" % e)
- path: /accounts/search-attribute-config/{name}
  method: GET
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/search-attribute-configuration#get-single-search-attribute-config
      source: |
        from sailpoint.v3.api.search_attribute_configuration_api import SearchAttributeConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.search_attribute_config import SearchAttributeConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          name = 'newMailAttribute' # str | Name of the extended search attribute configuration to retrieve. # str | Name of the extended search attribute configuration to retrieve.
          try:
              # Get Extended Search Attribute
              
              results = SearchAttributeConfigurationApi(api_client).get_single_search_attribute_config(name=name)
              # Below is a request that includes all optional parameters
              # results = SearchAttributeConfigurationApi(api_client).get_single_search_attribute_config(name)
              print("The response of SearchAttributeConfigurationApi->get_single_search_attribute_config:\n")
              for item in results:
                  print(item.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling SearchAttributeConfigurationApi->get_single_search_attribute_config: %s\n" % e)
- path: /accounts/search-attribute-config/{name}
  method: PATCH
  xCodeSample:
    - lang: Python
      label: SDK_tools/sdk/python/v3/methods/search-attribute-configuration#patch-search-attribute-config
      source: |
        from sailpoint.v3.api.search_attribute_configuration_api import SearchAttributeConfigurationApi
        from sailpoint.v3.api_client import ApiClient
        from sailpoint.v3.models.json_patch_operation import JsonPatchOperation
        from sailpoint.v3.models.search_attribute_config import SearchAttributeConfig
        from sailpoint.configuration import Configuration
        configuration = Configuration()


        with ApiClient(configuration) as api_client:
          name = 'promotedMailAttribute' # str | Name of the search attribute configuration to patch. # str | Name of the search attribute configuration to patch.
          json_patch_operation = '''[{op=replace, path=/name, value=newAttributeName}, {op=replace, path=/displayName, value=new attribute display name}, {op=add, path=/applicationAttributes, value={2c91808b79fd2422017a0b35d30f3968=employeeNumber}}]''' # List[JsonPatchOperation] | 
          try:
              # Update Extended Search Attribute
              new_json_patch_operation = JsonPatchOperation.from_json(json_patch_operation)
              results = SearchAttributeConfigurationApi(api_client).patch_search_attribute_config(name=name, json_patch_operation=new_json_patch_operation)
              # Below is a request that includes all optional parameters
              # results = SearchAttributeConfigurationApi(api_client).patch_search_attribute_config(name, new_json_patch_operation)
              print("The response of SearchAttributeConfigurationApi->patch_search_attribute_config:\n")
              print(results.model_dump_json(by_alias=True, indent=4))
          except Exception as e:
              print("Exception when calling SearchAttributeConfigurationApi->patch_search_attribute_config: %s\n" % e)
