templateDir: ./sdk-resources/resources
packageName: sailpoint.v2024
packageVersion: 1.3.3
apiVersion: v2024
generateSourceCodeOnly: true
funtionPrefix: V2024
subModuleName: V2024
files:
  developerSite_code_examples.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v2024/docs/Examples/python_code_examples_overlay.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v2024/docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v2024/Index.md
